---
output: 
  html_document: 
    keep_md: yes
---

# Cell area analysis

Cell area is stored in the database.


### 1. Make a movie of cell area pattern plotted on the tissue

* Copy-paste the following commands in the terminal:

```
tm sm make_db 
tm cell_area_pattern.R . output_analysis
```

```{r cell_area_pattern, warning=FALSE, message=FALSE, fig.width=11, cache=FALSE, eval=TRUE, echo=FALSE, results='hide'}
movieDir="/Users/retourna/MovieDB/demo"

scriptsDir=Sys.getenv("TM_HOME")
if(is.na(file.info(scriptsDir)$isdir)){
  stop(paste("TM_HOME not correctly defined (",scriptsDir ,")"))
}

source(file.path(scriptsDir, "commons/TMCommons.R"))
source(file.path(scriptsDir, "commons/BaseQueryFunctions.R"))
source(file.path(scriptsDir, "config/default_config.R"))

cellArea <- mqf_fg_cell_area(movieDir, rois = c("raw"), cellContour = T)

db <- openMovieDb(movieDir)

cellArea %>%
  render_frame(50) + 
  # we now map cell area values to a color palette: fill=area
  geom_polygon(aes(x_pos, y_pos, group=cell_id, fill=area), alpha=0.7) + 
  scale_fill_gradientn(name="area (px)",
                       colours=c("black", "blue", "green", "yellow", "red"),
                       limits=c(0,quantile(cellArea$area, probs = 99.9/100)),
                       na.value = "red") +
  ggtitle("cell_area_pattern")


```

[Where to find the results ?](../tm_qs_example_data.md#4-look-at-the-results) **|** 
[Back to tutorial list](../tm_qs_example_data.md#3-select-the-analysis-you-are-interested-in)

### 2. Plot cell area distrubution and averages
* Copy-paste the following commands in the terminal:

```
tm sm make_db 
tm cell_area_graphs.R . output_analysis
```

```{r cell_area_graphs, warning=FALSE, message=FALSE, fig.width=7, cache=FALSE, eval=TRUE, echo=FALSE,results='hide'}


movieDir="/Users/retourna/MovieDB/demo"

scriptsDir=Sys.getenv("TM_HOME")
if(is.na(file.info(scriptsDir)$isdir)){
  stop(paste("TM_HOME not correctly defined (",scriptsDir ,")"))
}


source(file.path(scriptsDir, "commons/TMCommons.R"))
source(file.path(scriptsDir, "commons/BaseQueryFunctions.R"))

mqf_cg_roi_cell_area(movieDir, rois = c("raw")) %>% 
  ggplot(aes(dev_time, area.avg, color=movie)) +
  geom_line() +
  xlab("Time [h]") +
  ylab("<Cell area> [px]")  +
  facet_wrap(~roi) +
  ggtitle("averaged_cell_area")

mqf_fg_cell_area(movieDir, rois = c("raw")) %>%
  ggplot(aes(area, fill=movie)) +
  geom_histogram(color="white") +
  xlab("Cell area [px]")  +
  facet_wrap(~roi) +
  ggtitle("cell_area_distribution")

mqf_fg_cell_area(movieDir, rois = c("raw")) %>%
  ggplot(aes(movie,area, fill=movie)) +
  geom_boxplot() +
  ylab("Cell area [px]")  +
  facet_wrap(~roi) +
  ggtitle("cell_area_boxplot")

mqf_fg_cell_area(movieDir, rois = c("raw")) %>%
  ggplot(aes(movie,area, fill=movie)) +
  geom_violin() +
  ylab("Cell area [px]")  +
  facet_wrap(~roi) +
  ggtitle("cell_area_violin")
```

[Where to find the results ?](../tm_qs_example_data.md#4-look-at-the-results) **|** 
[Back to tutorial list](../tm_qs_example_data.md#3-select-the-analysis-you-are-interested-in)

### 3. For further details

* compare multiple movies and ROI's, see [TM R User Manual](https://mpicbg-scicomp.github.io/tissue_miner/user_manual/TM_R-UserManual.html#comparing-averaged-quantities-between-movies-and-rois)
