
# First Use of TissueMiner from the command line

You'd like to use Tissue Miner for the **first time** ? Please follow the prodecure below to try it on the small Demo sample that contains images of segmented and tracked cells (pre-processed in TissueAnalyzer).


## 1. Open a terminal

* Ubuntu: just open a [terminal](https://help.ubuntu.com/community/UsingTheTerminal)

* Other systems (Mac and Windows): open a "Docker Quick Start Terminal". 
Once you have installed the [Docker engine](https://docs.docker.com/), click on "Docker Quickstart Terminal" in your Application folder or ProgramFile menu.




## 2. Download some example data (~100mb)

Just copy and paste the lines below into your terminal and press Enter:
```
     ## In your terminal, type in the command below to download and extract the Demo data
     curl https://cloud.mpi-cbg.de/index.php/s/EspCWSQn3k6NKLA/download  | tar -zxvf -
```

## 3. Select the analysis you are interested in

* [Cell area]()
* [Cell elongation]()
* [Cell packing]()
* [Cell lineage]()
* [Cell rearrangements]()
* [Cell contributions to tissue shear]()
* [Cell contributions to tissue area changes]()





## 3. Example for a cell area analysis

Cell area is stored in the database. It is therefore sufficient to build the databse only.

### 2.1 Run TissueMiner in a terminal to build the database

TissueMiner automatically performs a number of tasks that we defined in the *snakemake* workflow engine (abraviated sm). The workflow engine helps to run multiple tasks in the right order. To build a database from tracked cell data, TissueMiner uses the snakemake workflow engine with the option *make_db*.

* On Ubuntu: in your terminal, type in:
```
cd example_movie/demo_ForTissueMiner ## Go into the movie folder for further analysis
sm make_db # To build the database 

```

* On other operating systems: in the Docker Quick Start Terminal, type in:
```
cd example_movie/ ## Go into the movie repository folder for further analysis
docker run --rm -ti -v $(pwd):/movies -w /movies/demo_ForTissueMiner brandl/tissue_miner sm make_db # To build the database
```


### 2.2 Analysis in R: start Rstudio and open the R script called *cell_area.R* that you'll find in your local installation:
tissue_miner>docs>quickstart


```

```

### 2.3 Analysis in Python: please refer to the [Py-TM tutorial]()


For other types of analysis, please visite the [tutorial page]()

############# TUTO PAGE #######################

### 3.1 Cell elongation

Cell elongation is stored in the database. It is therefore sufficient to build the databse only.

* On Ubuntu: in your terminal, type in:
```
cd example_movie/demo_ForTissueMiner ## Go into the movie folder for further analysis
sm make_db # To build the database 

```

* On other operating systems: in the Docker Quick Start Terminal, type in:
```
cd example_movie/ ## Go into the movie repository folder for further analysis
docker run --rm -ti -v $(pwd):/movies -w /movies/demo_ForTissueMiner brandl/tissue_miner sm make_db # To build the database
```

* Analysis in R : Start Rstudio and open the R script entitled cell_elongation.R

* For more detailed information about R scripts, please refer to the [R-TM manual]()

* Analysis in Python: please refer to the [Py-TM tutorial]()


### 3.2 Cell packing

Cell packing analysis requires to build the database and to identify and count neighbors of each cell. This is automatically calculated in TissueMiner using the option *polygon_class*.

* On Ubuntu: in your terminal, type in:
```
cd example_movie/demo_ForTissueMiner ## Go into the movie folder for further analysis
sm polygon_class  

```

* On other operating systems: in the Docker Quick Start Terminal, type in:
```
cd example_movie/ ## Go into the movie repository folder for further analysis
docker run --rm -ti -v $(pwd):/movies -w /movies/demo_ForTissueMiner brandl/tissue_miner sm polygon_class
```

* Analysis in R : Start Rstudio and open the R script entitled cell_packing.R

* For more detailed information about R scripts, please refer to the [R-TM manual]()

* Analysis in Python: please refer to the [Py-TM tutorial]()


### 3.3 Cell lineage

Cell lineage analysis requires to build the database and to identify cell lineage graphs. This is automatically calculated in TissueMiner using the option *lineage_movies*.

* On Ubuntu: in your terminal, type in:
```
cd example_movie/demo_ForTissueMiner ## Go into the movie folder for further analysis
sm lineage_movies  

```

* On other operating systems: in the Docker Quick Start Terminal, type in:
```
cd example_movie/ ## Go into the movie repository folder for further analysis
docker run --rm -ti -v $(pwd):/movies -w /movies/demo_ForTissueMiner brandl/tissue_miner sm lineage_movies
```

* Analysis in R : Start Rstudio and open the R script entitled cell_lineage.R

* For more detailed information about R scripts, please refer to the [R-TM manual]()

* Analysis in Python: please refer to the [Py-TM tutorial]()



### 3.4 Cell rearrangements

### 3.5 Cell contributions to tissue shear

### 3.6 Cell contributions to tissue area changes


